baseURL = "https://oreoinhell.github.io"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "奥利奥的深坑"
copyright = "是的，这里都是oreoinhell写的，写起来还挺麻烦的。"
theme = "diary"
hasCJKLanguage = true
enableRobotsTXT = true

# Generate sitemap in the public folder
[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 0.5

# Google Analytics
[services]
  [services.googleAnalytics]
    id = "G-LR8NJ73YSL"  # Your Google Analytics ID

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4


[params]
subtitle = "Themed by Diary."
enableGitalk = false
enableGiscus = true
favicon = "favicon.ico"
enableReadingTime = true
customCSS = ["css/custom.css"]

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = "uys15bb3eo"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "奥利奥的深坑" 
description = "一个比较玄妙的地方。"


# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="oreoinhell/comments"
    data_repo_id="R_kgDOPFv73Q"
    data_category="General"
    data_category_id="DIC_kwDOPFv73c4CsYiV"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="en"
    crossorigin="anonymous"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
[[menu.main]]
url = "https://archiveofourown.org/users/oreo_one"
name = "AO3"
weight = 4
[[menu.main]]
url = "/stargazing"
name = "Starmap"
weight = 5
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 6
[[menu.main]]
url = "/about"
name = "About Me"
weight = 7